# Generated by Django 4.0.5 on 2022-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_available_quantity_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
