# Generated by Django 4.0.5 on 2022-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_rename_created_at_order_order_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Varification Pending'), (2, 'Varified'), (3, 'Delivered')], default=1, max_length=30),
        ),
    ]
